### PR TITLE
update gcc-arm-none-eabi-54.rb

### PR DESCRIPTION
**Pull request by jakerockland**
updated to reflect 5-2016-q3-update release to 5_4

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I don't think you intended to send a pull request.

**Comment by jakerockland** [comment]
@LorenzMeier I goofed a little bit 😓 I did mean to originally make this pull request, but only up to this commit: https://github.com/PX4/homebrew-px4/pull/10/commits/96fce71ae3fdff56b6e244727744efc9cf9eff79

Was a bit late last night when I made this change and I didn't mean to have all of my other changes to the repo on this PR. Will make a new PR though if it is something you find useful.

**Comment by LorenzMeier** [comment]
Yeah that one looked good - please send!

**Comment by jakerockland** [comment]
@LorenzMeier I made a new PR #11

**Pull request closed without merging**
