### PR TITLE
Bump gazebo version to 9

### PR DESCRIPTION
**Pull request by TSC21**
It came to my attention that the `px4-sim` formula still depends on Gazebo 8, instead of 9, which is now used as the standard Gazebo version on PX4. I am not aware of compatibility issues regarding the OSX version, so if someone someone is aware that this could not work, let me know.

### CODE REVIEW

**Comment by TSC21** [comment]
This repository had a `.travis.yaml` but wasn't added to Travis so to trigger the builds. Just did that. Also, added a parallel build to macOS Sierra so to avoid incompatibilities.

**Comment by TSC21** [comment]
Sierra is failing with numpy symlink. Can't tell if it's better to just remove that build job or not, since in the end the symlink can be solved a an overwrite command. Though this is not the purpose of this test.

**Comment by LorenzMeier** [comment]
Build is still failing.

**Comment by TSC21** [comment]
@LorenzMeier thanks for the fix, though the problem persists. I think I have the solution for this.

**Comment by LorenzMeier** [comment]
Gazebo 9 looks pretty broken on Mac OS - have you tested it?

screenshot 2018-12-02 at 14 56 14

**Comment by TSC21** [comment]
Not really. I saw most of the developers working with it though. Never thought it was broken. I leave that to your consideration

**Comment by LorenzMeier** [comment]
Let's leave that here until Gazebo 9 is actually working.

**Pull request closed without merging**
