### PR TITLE
workaround to fix genromfs patching

### PR DESCRIPTION
**Pull request by TSC21**
@dagar

### CODE REVIEW

**Comment by TSC21** [comment]
Fixes https://github.com/PX4/homebrew-px4/issues/22

**Comment by dagar** [comment]
I'm not really set up to test this. Feel free to merge if it works.

**Comment by TSC21** [comment]
I don't have write permissions

**Comment by dagar** [comment]
Fixes https://github.com/PX4/homebrew-px4/issues/22

**Comment by dagar** [comment]
Thanks!

**Pull request merged**
