### PR TITLE
Fix style errors, try to compile PX4 again

### PR DESCRIPTION
**Pull request by pietrodn**
Homebrew complains about some Formula errors in description strings: they are fixed.

Also, try to update the commands to compile PX4.

### CODE REVIEW

**Comment by TSC21** [comment]
@pietrodn is it fine to wait for https://github.com/PX4/homebrew-px4/pull/53? I already brought these fixes there.

**Comment by pietrodn** [comment]
Whoops, my bad. Feel free to close this PR after yours is merged. :-)

**Comment by TSC21** [comment]
> Whoops, my bad. Feel free to close this PR after yours is merged. :-)

There's just a little validation step required, otherwise it could have been merged earlier.

**Comment by TSC21** [comment]
Thanks for the contribution!

**Comment by julianoes** [comment]
@TSC21 can we just merge this already? It seems good like that.

**Comment by TSC21** [comment]
Supersede in #53

**Pull request closed without merging**
